server {
	# override 127.0.0.1:80 -> 301 127.0.0.1:8443
	listen 80;
	server_name localhost;
	return 301 https://$host:8443$request_uri;
}

server {
	# enable SSL
	listen 443 ssl;
	server_name localhost;

	### SSL configuration block ###
	ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
	ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;
	ssl_protocols TLSv1.3;
	ssl_prefer_server_ciphers off;

	add_header X-Frame-Options "SAMEORIGIN";
	add_header X-Content-Type-Options "nosniff";
	add_header X-XSS-Protection "1; mode=block";
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
	add_header Referrer-Policy "strict-origin-when-cross-origin";
	### end SSL configuration block ###

	# Wordpress
	root /var/www/html;
	index index.php index.html;
	client_max_body_size 64M;
	location / { try_files $uri $uri/ /index.php?$args; }

	# Wordpress child
	location ~ \.php$ {
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_read_timeout 300;
	}

	# Wordpress Media
	location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
		expires 30d;
		add_header Cache-Control "public, no-transform";
		access_log off;
	}

	# Force deny git
	location ~ /\.(ht|git) { deny all; }

	# netdata
	location /nginx_status {
		stub_status on; allow 172.0.0.0/8; deny all;
	}
}
